$(document).ready(function(){
	$("#flip1").click(function(){
		$("#panel1").slideDown("slow",function(){
			$("flip1").hide();
		});
	});
	$("#flipped1").click(function(){
		$("#panel1").slideUp("slow",function(){
			$("flip1").show();
		});
	});
	$("#flip2").click(function(){
		$("#panel2").slideToggle("slow");
	});
	$("#flip2A").click(function(){
		$("#panel2A").slideToggle("slow");
	});
	$("#flip2B").click(function(){
		$("#panel2B").slideToggle("slow");
	});
	$("#flip2C").click(function(){
		$("#panel2C").slideToggle("slow");
	});
	$("#flip2D").click(function(){
		$("#panel2D").slideToggle("slow");
	});
	$("#flip3").click(function(){
		$("#panel3").slideToggle("slow");
	});
	$("#flip4").click(function(){
		$("#panel4").slideToggle("slow");
	});
	$("#flip5").click(function(){
		$("#panel5").slideToggle("slow");
	});
	$("#flip6").click(function(){
		$("#panel6").slideToggle("slow");
	});
});
