$(document).ready(function(){
	$("#flip1").click(function(){
		$("#panel1").slideToggle("slow",function(){
			$("#flip1").replaceWith("<div id=\"flipped1\">Transportation -</div>");
		});
	});
	$("#flipped1").click(function(){
		$("#panel1").slideToggle("slow",function(){
			$("flipped1").replacewith("<div id=\"flip1\">Transportation	+</div>");
		});
	});
	$("#flip2").click(function(){
		$("#panel2").slideToggle("slow");
	});
	$("#flip2A").click(function(){
		$("#panel2A").slideToggle("slow");
	});
	$("#flip2B").click(function(){
		$("#panel2B").slideToggle("slow");
	});
	$("#flip2C").click(function(){
		$("#panel2C").slideToggle("slow");
	});
	$("#flip2D").click(function(){
		$("#panel2D").slideToggle("slow");
	});
	$("#flip3").click(function(){
		$("#panel3").slideToggle("slow");
	});
	$("#flip4").click(function(){
		$("#panel4").slideToggle("slow");
	});
	$("#flip5").click(function(){
		$("#panel5").slideToggle("slow");
	});
	$("#flip6").click(function(){
		$("#panel6").slideToggle("slow");
	});
	$("#flip1").mouseenter(function(){
		$("#flip1").fadeTo("fast",0.5);
	});
	$("#flip1").mouseleave(function(){
		$("#flip1").fadeTo(500,1.0);
	});
	$("#flipped1").mouseenter(function(){
		$("#flipped1").fadeTo("fast",0.5);
	});
	$("#fliped").mouseleave(function(){
		$("#flipped1").fadeTo(500,1.0);
	});
	$("#flip2").mouseenter(function(){
		$("#flip2").fadeTo("fast",0.5);
	});
	$("#flip2").mouseleave(function(){
		$("#flip2").fadeTo(500,1.0);
	});
	$("#flip3").mouseenter(function(){
		$("#flip3").fadeTo("fast",0.5);
	});
	$("#flip3").mouseleave(function(){
		$("#flip3").fadeTo(500,1.0);
	});
	$("#flip4").mouseenter(function(){
		$("#flip4").fadeTo("fast",0.5);
	});
	$("#flip4").mouseleave(function(){
		$("#flip4").fadeTo(500,1.0);
	});
	$("#flip5").mouseenter(function(){
		$("#flip5").fadeTo("fast",0.5);
	});
	$("#flip5").mouseleave(function(){
		$("#flip5").fadeTo(500,1.0);
	});
	$("#flip6").mouseenter(function(){
		$("#flip6").fadeTo("fast",0.5);
	});
	$("#flip6").mouseleave(function(){
		$("#flip6").fadeTo(500,1.0);
	});
	$("#flip2A").mouseenter(function(){
		$("#flip2A").fadeTo("fast",0.5);
	});
	$("#flip2A").mouseleave(function(){
		$("#flip2A").fadeTo(500,1.0);
	});
	$("#flip2B").mouseenter(function(){
		$("#flip2B").fadeTo("fast",0.5);
	});
	$("#flip2B").mouseleave(function(){
		$("#flip2B").fadeTo(500,1.0);
	});
	$("#flip2C").mouseenter(function(){
		$("#flip2C").fadeTo("fast",0.5);
	});
	$("#flip2C").mouseleave(function(){
		$("#flip2C").fadeTo(500,1.0);
	});
	$("#flip2D").mouseenter(function(){
		$("#flip2D").fadeTo("fast",0.5);
	});
	$("#flip2D").mouseleave(function(){
		$("#flip2D").fadeTo(500,1.0);
	});
});
