$(document).ready(function(){
	$("#f1").hover(function(){
		$("#f1").animate({
			'background-color':'#AAA',
			'color':'#555'
		},function(){
			$("#f1").animate({
				'background-color':'#FFF'
			},"slow");
		});
	});
	$("#f1").click(function(){
		$("#panel1").slideDown("slow",function(){
			$("#fd1").show();
			$("#f1").hide();
		});
	});
	$("#fd1").click(function(){
		$("#panel1").slideUp("slow",function(){
			$("#f1").show();
			$("#fd1").hide();
		});
	});
	$("#f2").click(function(){
		$("#panel2").slideDown("slow",function(){
			$("#fd2").show();
			$("#f2").hide();
		});
	});
	$("#fd2").click(function(){
		$("#panel2").slideUp("slow",function(){
			$("#f2").show();
			$("#fd2").hide();
		});
	});
	$("#f2A").click(function(){
		$("#panel2A").slideDown("slow",function(){
			$("#fd2A").show();
			$("#f2A").hide();
		});
	});
	$("#fd2A").click(function(){
		$("#panel2A").slideUp("slow",function(){
			$("#f2A").show();
			$("#fd2A").hide();
		});
	});
	$("#f2B").click(function(){
		$("#panel2B").slideDown("slow",function(){
			$("#fd2B").show();
			$("#f2B").hide();
		});
	});
	$("#fd2B").click(function(){
		$("#panel2B").slideUp("slow",function(){
			$("#f2B").show();
			$("#fd2B").hide();
		});
	});
	$("#f2C").click(function(){
		$("#panel2C").slideDown("slow",function(){
			$("#fd2C").show();
			$("#f2C").hide();
		});
	});
	$("#fd2C").click(function(){
		$("#panel2C").slideUp("slow",function(){
			$("#f2C").show();
			$("#fd2C").hide();
		});
	});
	$("#f2D").click(function(){
		$("#panel2D").slideDown("slow",function(){
			$("#fd2D").show();
			$("#f2D").hide();
		});
	});
	$("#fd2D").click(function(){
		$("#panel2D").slideUp("slow",function(){
			$("#f2D").show();
			$("#fd2D").hide();
		});
	});
	$("#f3").click(function(){
		$("#panel3").slideDown("slow",function(){
			$("#fd3").show();
			$("#f3").hide();
		});
	});
	$("#fd3").click(function(){
		$("#panel3").slideUp("slow",function(){
			$("#f3").show();
			$("#fd3").hide();
		});
	});
	$("#f4").click(function(){
		$("#panel4").slideDown("slow",function(){
			$("#fd4").show();
			$("#f4").hide();
		});
	});
	$("#fd4").click(function(){
		$("#panel4").slideUp("slow",function(){
			$("#f4").show();
			$("#fd4").hide();
		});
	});
	$("#f5").click(function(){
		$("#panel5").slideDown("slow",function(){
			$("#fd5").show();
			$("#f5").hide();
		});
	});
	$("#fd5").click(function(){
		$("#panel5").slideUp("slow",function(){
			$("#f5").show();
			$("#fd5").hide();
		});
	});
	$("#f6").click(function(){
		$("#panel6").slideDown("slow",function(){
			$("#fd6").show();
			$("#f6").hide();
		});
	});
	$("#fd6").click(function(){
		$("#panel6").slideUp("slow",function(){
			$("#f6").show();
			$("#fd6").hide();
		});
	});
});
